import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import "./globals.css";
import { ConfigProvider, Layout } from "antd";
import { NavBar } from "@/components/nav-bar";
import { CustomHeader } from "@/components/header";
import { Body } from "@/components/body";
import { CustomFooter } from "@/components/footer";
import { NavLinks } from "@/components/nav-links";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const locale = await getLocale();
    const messages = await getMessages();

    return (
        <html lang={locale}>
            <body>
                <ConfigProvider>
                    <NextIntlClientProvider messages={messages}>
                        <Layout className="app-layout">
                            <CustomHeader></CustomHeader>
                            <Layout className="main-layout">
                                <NavBar></NavBar>
                                <Layout className="content-layout">
                                    <NavLinks></NavLinks>
                                    <Body>{children}</Body>
                                    <CustomFooter></CustomFooter>
                                </Layout>
                            </Layout>
                        </Layout>
                    </NextIntlClientProvider>
                </ConfigProvider>
            </body>
        </html>
    );
}
