import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Layout } from "antd";
import { Header, Footer, Content } from "antd/es/layout/layout";
import Sider from "antd/es/layout/Sider";
import { NavLinks } from "@/components/nav-links";
import { NavBar } from "@/components/nav-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Layout style={{ minHeight: "100vh" }}>
          <Sider collapsible>
            <div className="demo-logo-vertical" />
            <NavBar></NavBar>
          </Sider>
          <Layout>
            <Header style={{ padding: 0 }} />
            <Content style={{ margin: "0 16px" }}>
              <NavLinks></NavLinks>
              <AntdRegistry>{children}</AntdRegistry>
            </Content>
            <Footer style={{ textAlign: "center" }}>
              Ant Design ©{new Date().getFullYear()} Created by Ant UED
            </Footer>
          </Layout>
        </Layout>
      </body>
    </html>
  );
}
